sudo: required
language: bash

services:
  - docker

cache:
  - ccache: true
  - directories:
      - $HOME/Library/Caches/Homebrew

matrix:
  include:
    - os: linux
      env:
        - VM=ubuntu
        - TAG=16.04
    - os: linux
      env:
        - VM=ubuntu
        - TAG=18.04
    - os: linux
      env: 
        - VM=mxe
        - TAG=qt-5.12
    - os: osx
      compiler: clang

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew install https://homebrew.bintray.com/bottles/qt-5.13.2.high_sierra.bottle.tar.gz net-snmp ;
      brew upgrade openssl cmake ;
    fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker pull fwbuilder/$VM:$TAG ;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker run -v $(pwd):/fwbuilder -v $HOME/.ccache:/root/.ccache -it fwbuilder/$VM:$TAG "/fwbuilder/docker/travis.${VM}_${TAG}.sh" ;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export PATH="/usr/local/opt/qt/bin:/usr/local/opt/net-snmp/bin:$PATH" ;
      export OPENSSL_ROOT_DIR="/usr/local/opt/openssl" ;
      mkdir build ;
      cd build ;
      cmake .. ;
      make -j$(sysctl -n hw.ncpu) install ;
    fi

